[build-system]
requires = [
    "setuptools",
    "wheel",
    "cartopy",
    "dsmpy",
    'obspy',
    'mpi4py',
    'pandas',
    'matplotlib',
    'geographiclib',
    "numpy",
    "sklearn",
    "seaborn",
]
build-backend = 'setuptools.build_meta'